swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"
definitions:
  Address:
    type: object
    required:
      - houseno
      - locality
      - city
    properties:
      houseno:
        type: string
      locality:
        type: string
      city:
        type: string
  Person:
    type: object
    required:
      - fname
      - lname
      - email
      - address
    properties:
      fname:
        type: string
        description: user first name
      lname:
        type: string
        description: user last name
      email:
        type: string
        description: people email
      address:
        $ref: "#/definitions/Address"
        description: address
  People:
    type: object
    required:
      - results
    properties:
      results:
        type: array
        items:
          $ref: "#/definitions/Person"
  Error:
    type: object
    properties:
      code:
        type: integer
        description: the http status code
        minimum: 400
        maximum: 599
      message:
        type: string
basePath: "/api"

paths:
  /people:
    get:
      operationId: "swagapi_demo.people.get"
      tags:
        - "People"
      summary: "People data structure supported by Server"
      description: "List of People"
      responses:
        200:
          description: "Successful read of the list"
          schema:
            $ref: "#/definitions/People"
    post:
      operationId: "swagapi_demo.people.post"
      tags:
        - "People"
      summary: "People data structure supported by Server"
      description: "List of People"
      parameters:
        - name: Person
          schema:
            $ref: '#/definitions/Person'
          required: true
          in: body
      responses:
        200:
          description: "Succeeded"
        500:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
